dist: xenial
language: python
cache: pip

matrix:
  include:
    - python: 3.7

install:
  pip install --requirement=requirements.txt

script:
  - flake8
  - black --check .
  - mypy .
  - pytest --verbose -r s

