# Generated by Django 2.2.3 on 2019-07-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20190709_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.SlugField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.SlugField(max_length=64, unique=True),
        ),
    ]
